[tool.poetry]
name = "migibot"
version = "0.1.0"
description = "RAG Based Agent for insurance"
authors = ["GitHamza0206 <zeroualihamza0206@gmail.com>"]
readme = "README.md"
packages = [{include = "services"}]

[tool.poetry.dependencies]
python = "^3.11,<3.13"
langchain = "^0.3.13"
langgraph = "^0.2.60"
python-dotenv = "^1.0.1"
faiss-cpu = "^1.9.0.post1"
langchain-community = "^0.3.13"
langchain-openai = "^0.2.14"
uvicorn = "^0.34.0"
fastapi = "^0.115.6"
markdown = "^3.7"
unstructured = {extras = ["local-inference"], version = "^0.16.12"}
langchain-chroma = "^0.1.4"
markitdown = "^0.0.1a3"
litellm = "^1.56.6"
python-multipart = "^0.0.20"
pytest = "^8.3.4"
pytest-asyncio = "^0.25.2"
pillow-heif = "^0.21.0"
pdf2image = "^1.17.0"
pdfminer-six = "20221105"
docling = "^2.15.1"
langchain-docling = "^0.2.0"
ipykernel = "^6.29.5"
vllm = "^0.6.6.post1"
ollama = "^0.4.6"
langchain-ollama = "^0.2.2"
pdfplumber = "^0.10.3"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
